### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by chimosky**
@quozl kindly review.

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
Thanks. Reviewed.
Though it was a bit difficult to compare the changes for 'utils.py' file. Github shows every line changed for that file, but it clearly it's not the case. I don't find many actual changes in the 'utils.py' file. Use of '2to3' for porting results in this sometimes.

**Comment by quozl** [comment]
Was caused by the files haveing CRLF line terminators, which is DOS
format.

I've converted them and pushed
9eb60d389a4f08b7f634771f6b1f0db6a0983bea.

Please rebase.

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed.  Merged by hand to fix the commit messages; extraneous period at end of line, and didn't follow established style.

**Pull request closed without merging**
